service:
  image: quay.io/flypenguin/rancon
  entrypoint: ./rancher.sh
  command: -b url=${consul_url}
  labels:
    # http://docs.rancher.com/rancher/v1.0/zh/rancher-services/service-accounts/
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
