.catalog:
  name: cvs-service
  version: "2.6async"
  description: |
    Creates a CVS-RSAS combination and tags it for the load balancer. Relies on
    a running cousul-router-based infrastructure to be picked up.
  questions:

    - variable: service_url
      label: URL for service
      description: "Do not enter the TLD, AND USE TWO DASHES INSTEAD OF A DOT!!"
      required: true
      type: string

    - variable: staging_prefix
      label: Prefix the API with this
      description: "For production, choose 'p'"
      default: p
      required: false
      type: string

    - variable: service_type
      label: Visibility
      description: "Choose 'webui_external' for reachability from 'outside'"
      type: enum
      options:
        - webui
        - webui_external
      required: true

    - variable: s3_bucket
      label: S3 bucket
      description: "The S3 bucket to use for caching 'RSAS' packages"
      default: cognotekt.health
      required: true
      type: string

    - variable: aws_access_key
      label: AWS access key
      description: "not neccessary (hopefully) if instance has IAM role attached"
      type: string

    - variable: aws_secret_key
      label: AWS secret key
      description: "not neccessary (hopefully) if instance has IAM role attached"
      type: string

    - variable: dispatcher_image
      label: Dispatcher container
      description: "(formerly RSAS)"
      default: hub.cognotekt.int:5000/production/rsas:dev-async
      required: true
      type: string

    - variable: dispatcher_image
      label: Dispatcher container
      description: "(formerly RSAS)"
      default: hub.cognotekt.int:5000/production/rsas:dev-async
      required: true
      type: string


    - variable: redis_image
      label: redis container
      description: Atomic counter for incrementing.
      default: redis
      required: true
      type: string

    - variable: cvs_image
      label: CVS container
      description: Base container image for CVS
      default: hub.cognotekt.int:5000/production/cvs:latest
      required: true
      type: string

    - variable: sqs_queue
      label: CVS container
      description: sqs queue
      default: test_queue
      required: true
      type: string

    - variable: sqs_queue1
      label: CVS container
      description: sqs queue
      default: dev_queue
      required: true
      type: string

    - variable: cvs_config_image
      label: CVS configuration container
      description: Select CVS configuration
      default: hub.cognotekt.int:5000/production/config:latest
      required: true
      type: string

    - variable: log_destination_host
      label: Send logs to this host
      description: TCP connection sending strings ending with newline
      default: health.logstash.service.consul
      required: true
      type: string

    - variable: log_destination_port
      label: Try to connect this port for log sending
      description: The port to connect to
      default: 8901
      required: true
      type: int

    - variable: prometheus_pushgateway_address
      label: The prometheus pushgateay address
      description: "specify 'consul:<service-name>' for a lookup in consul, or 'dummy' if there isn't one"
      default: consul:pushgateway
      required: true
      type: string


processor:
  scale: 2

dispatcher:
  scale: 1
  health_check:
    port: 1194
    interval: 5000
    unhealthy_threshold: 2
    request_line: GET /health HTTP/1.0
    healthy_threshold: 3
    response_timeout: 5000

statistics-component:
  scale: 1

redis:
  scale: 1

cvs-balancer:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 5000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000

