.catalog:
  name: owncloud-cognotekt
  version: "0.0.1"
  description: |
    Creates a global set of load balancers on hosts with a certain label which
    balance traffic into a Rancher-internal service stack
  uuid: owncloud-cognotekt-0
  questions:

    - variable: database_host
      label: Database host URL
      description: Must be URL, use "db" as database host name in owncloud
      required: true
      type: string

owncloud:
  scale: 1
  health_check:
    port: 80
    interval: 5000
    request_line: GET / HTTP/1.0
    unhealthy_threshold: 4
    healthy_threshold: 4
    response_timeout: 4000

owncloud-db:
  hostname: ${database_host}

owncloud-data:
  scale: 1
