carsresale-crawler:
  image: ${carsresale_crawler_image}
  ports:
    - 5000:5000
  environment:
    SCRAPY_API_KEY: ${scrapy_api_key}
    AWS_ACCESS_KEY_ID: ${aws_acces_key_id}
    AWS_SECRET_ACCESS_KEY: ${aws_secret_access_key}
    DEBUG: false
  labels:
    rancon.name: ${service_url}
    rancon.tag: ${service_type}
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
