cfgtool:
  image: ${cfgtool_image}
  ports:
    - "8000"
  environment:
    DB_CONNECTION: ${config_db_connection}
    DB_PASSWORD: ${config_db_password}
    ADMIN_PASSWORD: ${cfg_admin_password}
    DEBUG: False
  labels:
    rancon.name: ${service_url}
    rancon.tag: ${service_type}
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.pull_image: always
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
    io.rancher.container.hostname_override: container_name
