owncloud:
  image: owncloud
  ports:
    - "80"
  volumes:
    - /srv/owncloud:/var/www/html
  links:
    - owncloud-db:db
  labels:
    io.rancher.scheduler.affinity:host_label: owncloud=true
    rancon.name: owncloud

owncloud-db:
  image: rancher/external-service
