.catalog:
  name: owncloud-cognotekt
  version: "0.0.2-nossl"
  description: |
    Creates an owncloud instance on a host labeled "owncloud=true", which
    saves data to /srv/owncloud on the underlying host
  questions:

    - variable: database_host
      label: Database host URL
      description: Must be URL, use "db" as database host name in owncloud
      required: true
      type: string

owncloud:
  scale: 1

owncloud-db:
  hostname: ${database_host}
