.catalog:
  name: Pypi-Repository
  version: "1.0.0"
  description: |
    Deploys a Pypi Cloud Repository.
  questions:

    - variable: service_url
      label: URL for service
      description: "Do not enter the TLD, AND USE TWO DASHES INSTEAD OF A DOT!!"
      required: true
      type: string

    - variable: service_type
      label: Visibility
      description: "Choose 'webui_external' for reachability from 'outside'"
      type: enum
      options:
        - webui
        - webui_external
      required: true
     
    - variable: s3_bucket
      label: S3 bucket
      description: "The S3 bucket to use for storing 'pypi' packages"
      default: cognotekt-internal-artifacts
      required: true
      type: string

    - variable: aws_access_key
      label: AWS access key
      description: "not neccessary (hopefully) if instance has IAM role attached"
      type: string

    - variable: aws_secret_key
      label: AWS secret key
      description: "not neccessary (hopefully) if instance has IAM role attached"
      type: string


My-Py-repo:
  scale: 1
