.catalog:
  name: flask-webapp-tool
  version: "1.0.0"
  description: |
    Deploys a python flask web app.
  questions:

    - variable: service_url
      label: URL for service
      description: "Do not enter the TLD, AND USE TWO DASHES INSTEAD OF A DOT!!"
      required: true
      type: string

    - variable: service_type
      label: Visibility
      description: "Choose 'webui_external' for reachability from 'outside'"
      type: enum
      options:
        - webui
        - webui_external
      required: true


webapppython:
  scale: 1
